DROP TABLE IF EXISTS "Address";
CREATE TABLE "Address" ("address_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "zip_code" TEXT NOT NULL , "first_line" TEXT NOT NULL , "second_line" TEXT, "city" TEXT NOT NULL , "state" TEXT NOT NULL );
DROP TABLE IF EXISTS "Availability";
CREATE TABLE "Availability" ("availability_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "listing_id" INTEGER NOT NULL , "begin_date_time" TEXT NOT NULL , "end_date_time" TEXT NOT NULL , "is_reserved" BOOL DEFAULT FALSE);
DROP TABLE IF EXISTS "CancellationPolicy";
CREATE TABLE "CancellationPolicy" ("cancellation_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "cancellation_policy" TEXT NOT NULL );
INSERT INTO "CancellationPolicy" VALUES(1,'No Charge');
INSERT INTO "CancellationPolicy" VALUES(2,'Ten Percent of Charge');
INSERT INTO "CancellationPolicy" VALUES(3,'Five Dollar Charge');
INSERT INTO "CancellationPolicy" VALUES(4,'Ten Dollar Charge');
DROP TABLE IF EXISTS "Category";
CREATE TABLE "Category" ("category_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "category" TEXT NOT NULL  UNIQUE );
INSERT INTO "Category" VALUES(1,'Handicapped');
INSERT INTO "Category" VALUES(2,'Compact');
INSERT INTO "Category" VALUES(3,'Truck');
INSERT INTO "Category" VALUES(4,'SUV');
INSERT INTO "Category" VALUES(5,'Tandem');
INSERT INTO "Category" VALUES(6,'Covered');
DROP TABLE IF EXISTS "CategoryListing";
CREATE TABLE "CategoryListing" ("listing_id" INTEGER NOT NULL , "category_id" INTEGER NOT NULL );
DROP TABLE IF EXISTS "Lender";
CREATE TABLE "Lender" ("user_email" TEXT NOT NULL , "lender_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "phone_number" INTEGER, "profile_pic" BLOB, "is_default_role" BOOL);
DROP TABLE IF EXISTS "Listing";
CREATE TABLE "Listing" ("listing_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "lender_id" INTEGER NOT NULL , "listing_title" TEXT NOT NULL , "description" TEXT NOT NULL , "total_rating" INTEGER DEFAULT 0, "number_of_ratings" INTEGER DEFAULT 0, "cancellation_id" INTEGER NOT NULL , "address_id" INTEGER NOT NULL , "price_per_hr" INTEGER NOT NULL );
DROP TABLE IF EXISTS "ListingImage";
CREATE TABLE "ListingImage" ("listing_id" INTEGER NOT NULL , "image" BLOB NOT NULL );
DROP TABLE IF EXISTS "Reservation";
CREATE TABLE "Reservation" ("reservation_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "seeker_id" INTEGER NOT NULL , "lender_id" INTEGER NOT NULL , "listing_id" INTEGER NOT NULL , "availability_id" INTEGER NOT NULL , "amount_paid" DOUBLE NOT NULL , "transaction_id" INTEGER);
DROP TABLE IF EXISTS "Seeker";
CREATE TABLE "Seeker" ("user_email" TEXT NOT NULL , "seeker_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "phone_number" INTEGER NOT NULL , "profile_pic" BLOB, "is_default_role" BOOL);
DROP TABLE IF EXISTS "SeekerFavorites";
CREATE TABLE "SeekerFavorites" ("seeker_id" INTEGER NOT NULL , "listing_id" INTEGER NOT NULL );
DROP TABLE IF EXISTS "User";
CREATE TABLE "User" ("user_email" TEXT PRIMARY KEY  NOT NULL  UNIQUE , "password" TEXT NOT NULL , "name" TEXT NOT NULL );
